name: frontend
description: A simple incident reporting app
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  # Network & API
  http: ^1.1.0
  
  # Media handling
  image_picker: ^1.0.4
  path: ^1.8.3
  path_provider: ^2.1.1
  
  geolocator: ^13.0.2  # Update from 10.1.1
  async: ^2.13.0       # Update from 2.12.0
  geolocator_web: ^4.1.1  # Update from 2.2.1
  material_color_utilities: 0.11.1  # Update from 0.11.1
  shared_preferences: ^2.5.2
  flutter_spinkit: ^5.2.1
  video_player: ^2.9.5
